services:
  productservice:
    build: product-service
    volumes:
      - "./config:/config"
      - "./product-service/src:/code"
    secrets:
      - db_password
    networks:
      - backend
      - frontend
    depends_on:
      - db

  web:
    build: nginx
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - productservice

  db:
    image: mysql
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
      - "db-volume:/var/lib/mysql"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  db-volume:

networks:
  frontend:
  backend:

secrets:
  db_password:
    file: db_password.txt